// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahinpghodgwizjturmse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoaW5wZ2hvZGd3aXpqdHVybXNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjc3NDgsImV4cCI6MjA2MzYwMzc0OH0._8ZFDlNMo7KYytopm4KN388YPYb8XbMvvxBn8jCLsq8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);